<?php

declare(strict_types=1);

return [
    [
        'slug' => 'reto01-osint',
        'numero' => 1,
        'titulo' => 'Reconocimiento pasivo',
        'categoria' => 'Reconocimiento',
        'dificultad' => 'Facil',
        'puntaje' => 50,
        'objetivo' => 'Obtener informacion publica del objetivo sin interactuar directamente con el, identificando posibles mensajes olvidados o datos resagados.',
        'herramientas' => ['Terminal', 'inspeccion', 'busqueda avanzada'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto02-nmap',
        'numero' => 2,
        'titulo' => 'Descubrimiento de red',
        'categoria' => 'Reconocimiento',
        'dificultad' => 'Facil',
        'puntaje' => 75,
        'objetivo' => 'Identificar que hosts estan activos en la red objetivo mediante un escaneo inicial de alcance controlado.',
        'herramientas' => ['Nmap', 'ping sweep', 'ARP discovery'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto03-puertos',
        'numero' => 3,
        'titulo' => 'Escaneo de puertos',
        'categoria' => 'Enumeracion',
        'dificultad' => 'Media',
        'puntaje' => 100,
        'objetivo' => 'Detectar puertos abiertos en el objetivo para ubicar posibles puntos de entrada y priorizar la superficie expuesta.',
        'herramientas' => ['Nmap', 'TCP SYN scan', 'top ports'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto04-servicios',
        'numero' => 4,
        'titulo' => 'Enumeracion de servicios',
        'categoria' => 'Enumeracion',
        'dificultad' => 'Media',
        'puntaje' => 125,
        'objetivo' => 'Analizar servicios y versiones detectadas en los puertos abiertos para relacionarlos con configuraciones debiles o vulnerabilidades conocidas.',
        'herramientas' => ['Nmap -sV', 'banner grabbing', 'version detection'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto05-credenciales',
        'numero' => 5,
        'titulo' => 'Acceso por credenciales debiles',
        'categoria' => 'Explotacion inicial',
        'dificultad' => 'Media',
        'puntaje' => 125,
        'objetivo' => 'Intentar ingresar a un sistema utilizando combinaciones simples de usuario y contrasena derivadas del contexto del laboratorio.',
        'herramientas' => ['credenciales por defecto', 'Hydra', 'wordlists basicas'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto06-sqli-login',
        'numero' => 6,
        'titulo' => 'SQL Injection (login bypass)',
        'categoria' => 'Explotacion web',
        'dificultad' => 'Media',
        'puntaje' => 150,
        'objetivo' => 'Explotar una vulnerabilidad en el formulario de autenticacion para acceder sin credenciales validas.',
        'herramientas' => ['payloads SQLi', 'Burp Suite', 'pruebas manuales'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto07-sqli-datos',
        'numero' => 7,
        'titulo' => 'SQL Injection (extraccion de datos)',
        'categoria' => 'Explotacion web',
        'dificultad' => 'Alta',
        'puntaje' => 150,
        'objetivo' => 'Manipular consultas SQL para extraer informacion sensible desde la base de datos una vez identificado el vector de inyeccion.',
        'herramientas' => ['UNION SELECT', 'SQLMap', 'enumeracion manual'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto08-xss',
        'numero' => 8,
        'titulo' => 'XSS (Cross Site Scripting)',
        'categoria' => 'Explotacion web',
        'dificultad' => 'Alta',
        'puntaje' => 175,
        'objetivo' => 'Inyectar codigo JavaScript en la aplicacion para ejecutar acciones controladas dentro del navegador y demostrar impacto.',
        'herramientas' => ['payloads XSS', 'DevTools', 'context analysis'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto09-stego',
        'numero' => 9,
        'titulo' => 'Esteganografia',
        'categoria' => 'Analisis',
        'dificultad' => 'Alta',
        'puntaje' => 175,
        'objetivo' => 'Analizar una imagen o archivo entregado como evidencia para descubrir informacion oculta en su interior.',
        'herramientas' => ['strings', 'binwalk', 'steghide'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto10-cve',
        'numero' => 10,
        'titulo' => 'Analisis de vulnerabilidades (CVE)',
        'categoria' => 'Analisis',
        'dificultad' => 'Alta',
        'puntaje' => 200,
        'objetivo' => 'Investigar vulnerabilidades conocidas asociadas a un servicio detectado y preparar la estrategia de explotacion mas viable.',
        'herramientas' => ['NVD', 'Exploit-DB', 'searchsploit'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto11-metasploit',
        'numero' => 11,
        'titulo' => 'Explotacion con Metasploit',
        'categoria' => 'Explotacion',
        'dificultad' => 'Alta',
        'puntaje' => 225,
        'objetivo' => 'Utilizar un exploit validado para obtener acceso remoto al sistema objetivo de forma controlada.',
        'herramientas' => ['Metasploit', 'msfconsole', 'payloads'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto12-privesc',
        'numero' => 12,
        'titulo' => 'Escalada de privilegios',
        'categoria' => 'Post explotacion',
        'dificultad' => 'Experto',
        'puntaje' => 300,
        'objetivo' => 'Elevar permisos dentro del sistema comprometido hasta obtener acceso de administrador o root y cerrar la cadena de ataque.',
        'herramientas' => ['linpeas', 'sudo abuse', 'misconfiguraciones locales'],
        'estado' => 'Disponible',
    ],
];
