<?php

declare(strict_types=1);

return [
    [
        'slug' => 'reto01-osint',
        'numero' => 1,
        'titulo' => 'OSINT Inicial',
        'categoria' => 'Reconocimiento',
        'dificultad' => 'Facil',
        'puntaje' => 50,
        'objetivo' => 'Recopilar informacion pasiva del objetivo usando fuentes publicas.',
        'herramientas' => ['theHarvester', 'WHOIS', 'busqueda avanzada'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto02-nmap',
        'numero' => 2,
        'titulo' => 'Escaneo de Servicios',
        'categoria' => 'Reconocimiento',
        'dificultad' => 'Facil',
        'puntaje' => 75,
        'objetivo' => 'Descubrir puertos, versiones y posibles vectores de ataque en localhost.',
        'herramientas' => ['Nmap', 'banner grabbing'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto03-sqli',
        'numero' => 3,
        'titulo' => 'Inyeccion SQL',
        'categoria' => 'Web',
        'dificultad' => 'Media',
        'puntaje' => 100,
        'objetivo' => 'Explotar una autenticacion vulnerable y recuperar una bandera.',
        'herramientas' => ['SQLMap', 'payloads manuales'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto04-xss',
        'numero' => 4,
        'titulo' => 'XSS Reflejado y Almacenado',
        'categoria' => 'Web',
        'dificultad' => 'Media',
        'puntaje' => 100,
        'objetivo' => 'Ejecutar JavaScript controlado para capturar una pista sensible.',
        'herramientas' => ['payloads XSS', 'DevTools'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto05-upload',
        'numero' => 5,
        'titulo' => 'Subida de Archivos',
        'categoria' => 'Web',
        'dificultad' => 'Media',
        'puntaje' => 125,
        'objetivo' => 'Bypassear validaciones de subida y ejecutar codigo controlado.',
        'herramientas' => ['Burp Suite', 'payloads PHP'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto06-auth',
        'numero' => 6,
        'titulo' => 'Autenticacion Debil',
        'categoria' => 'Web',
        'dificultad' => 'Media',
        'puntaje' => 125,
        'objetivo' => 'Identificar malas practicas de sesion y privilegios.',
        'herramientas' => ['cookies', 'fuzzing basico'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto07-stego',
        'numero' => 7,
        'titulo' => 'Esteganografia',
        'categoria' => 'Analisis',
        'dificultad' => 'Media',
        'puntaje' => 150,
        'objetivo' => 'Extraer informacion oculta dentro de archivos multimedia.',
        'herramientas' => ['strings', 'binwalk', 'steghide'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto08-cve',
        'numero' => 8,
        'titulo' => 'Analisis de CVE',
        'categoria' => 'Analisis',
        'dificultad' => 'Alta',
        'puntaje' => 175,
        'objetivo' => 'Relacionar una version vulnerable con una explotacion conocida.',
        'herramientas' => ['NVD', 'exploit-db'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto09-metasploit',
        'numero' => 9,
        'titulo' => 'Automatizacion con Metasploit',
        'categoria' => 'Explotacion',
        'dificultad' => 'Alta',
        'puntaje' => 175,
        'objetivo' => 'Ejecutar una explotacion controlada y validar acceso.',
        'herramientas' => ['Metasploit', 'msfconsole'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto10-local',
        'numero' => 10,
        'titulo' => 'Escalada Local Simulada',
        'categoria' => 'Post Explotacion',
        'dificultad' => 'Alta',
        'puntaje' => 200,
        'objetivo' => 'Aprovechar configuraciones inseguras dentro de la maquina.',
        'herramientas' => ['linpeas', 'enumeracion manual'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto11-forensics',
        'numero' => 11,
        'titulo' => 'Forense Basico',
        'categoria' => 'Analisis',
        'dificultad' => 'Alta',
        'puntaje' => 200,
        'objetivo' => 'Reconstruir eventos a partir de archivos y registros comprometidos.',
        'herramientas' => ['logs', 'hashes', 'timeline'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto12-final',
        'numero' => 12,
        'titulo' => 'Reto Final Encadenado',
        'categoria' => 'Final',
        'dificultad' => 'Experto',
        'puntaje' => 300,
        'objetivo' => 'Combinar tecnicas de reconocimiento, explotacion y analisis para obtener la bandera final.',
        'herramientas' => ['cadena completa'],
        'estado' => 'Disponible',
    ],
];
