<?php

declare(strict_types=1);

return [
    [
        'slug' => 'reto01-osint',
        'numero' => 1,
        'titulo' => 'Reconocimiento pasivo',
        'categoria' => 'Reconocimiento',
        'dificultad' => 'Facil',
        'puntaje' => 50,
        'objetivo' => 'Obtener informacion publica del objetivo sin interactuar directamente con el, identificando posibles mensajes olvidados o datos resagados.',
        'herramientas' => ['Terminal', 'inspeccion', 'busqueda avanzada'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto02-nmap',
        'numero' => 2,
        'titulo' => 'Descubrimiento de red',
        'categoria' => 'Reconocimiento',
        'dificultad' => 'Facil',
        'puntaje' => 75,
        'objetivo' => 'Identificar que hosts estan activos en la red objetivo mediante un escaneo inicial de alcance controlado.',
        'herramientas' => ['Nmap', 'ping sweep', 'ARP discovery'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto03-puertos',
        'numero' => 3,
        'titulo' => 'Escaneo de puertos',
        'categoria' => 'Enumeracion',
        'dificultad' => 'Media',
        'puntaje' => 100,
        'objetivo' => 'Detectar puertos abiertos en el objetivo para ubicar posibles puntos de entrada y priorizar la superficie expuesta.',
        'herramientas' => ['Nmap', 'TCP SYN scan', 'top ports'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto04-servicios',
        'numero' => 4,
        'titulo' => 'Enumeracion de servicios',
        'categoria' => 'Enumeracion',
        'dificultad' => 'Media',
        'puntaje' => 125,
        'objetivo' => 'Analizar servicios y versiones detectadas en los puertos abiertos para relacionarlos con configuraciones debiles o vulnerabilidades conocidas.',
        'herramientas' => ['-sV', 'banner grabbing', 'version detection'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto05-credenciales',
        'numero' => 5,
        'titulo' => 'Acceso a un servicio descubierto',
        'categoria' => 'Explotacion inicial',
        'dificultad' => 'Media',
        'puntaje' => 125,
        'objetivo' => 'Se ha identificado un servicio web adicional durante la fase de enumeración. 
            Explora este servicio y analiza su contenido en busca de información expuesta o accesos inseguros.',
        'herramientas' => ['Navegador web', 'DevTools (inspección de elementos)', 'análisis de respuestas HTTP'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto06-sqli-login',
        'numero' => 6,
        'titulo' => 'SQL Injection (login bypass)',
        'categoria' => 'Explotacion web',
        'dificultad' => 'Media',
        'puntaje' => 150,
        'objetivo' => 'Se ha identificado un formulario de autenticación dentro del servicio web. 
            Analiza cómo se procesan los datos ingresados y determina si es posible acceder sin credenciales válidas. login.php',
        'herramientas' => ['payloads SQLi', 'Navegador web', 'pruebas manuales de inyección SQL'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto07-sqli-datos',
        'numero' => 7,
        'titulo' => 'SQL Injection (extraccion de datos)',
        'categoria' => 'Explotacion web',
        'dificultad' => 'Alta',
        'puntaje' => 150,
        'objetivo' => 'Manipula consultas SQL para extraer información sensible desde la base de datos.
            El sistema valida credenciales, pero podría estar construyendo consultas de forma insegura.
            Tu objetivo es ir más allá del login y obtener datos ocultos. login1.php',
        'herramientas' => ['UNION SELECT', 'Inyección SQL manual', 'Enumeración de columnas (ORDER BY)',
            'Pruebas directamente en los campos del login'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto08-xss',
        'numero' => 8,
        'titulo' => 'XSS (Cross Site Scripting)',
        'categoria' => 'Explotacion web',
        'dificultad' => 'Alta',
        'puntaje' => 175,
        'objetivo' => 'Este servicio permite a los usuarios publicar comentarios que son mostrados en tiempo real en la aplicación.
            Tu objetivo es analizar cómo se procesa la entrada del usuario e identificar si es posible ejecutar código en el navegador. xss.php',
        'herramientas' => ['Nmap', 'searchsploit', 'NVD', 'CVEs conocidas'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto09-stego',
        'numero' => 9,
        'titulo' => 'Esteganografia',
        'categoria' => 'Analisis',
        'dificultad' => 'Alta',
        'puntaje' => 175,
        'objetivo' => 'Se ha detectado que uno de los archivos disponibles contiene información oculta.
            Analiza cuidadosamente la imagen y determina si contiene datos adicionales incrustados.',
        'herramientas' => ['Exiftool', 'Terminal', 'Propiedades del archivo','strings'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto10-cve',
        'numero' => 10,
        'titulo' => 'Analisis de vulnerabilidades (CVE)',
        'categoria' => 'Analisis',
        'dificultad' => 'Alta',
        'puntaje' => 200,
        'objetivo' => 'Se ha identificado un servicio potencialmente vulnerable ejecutándose en el sistema.
            Analiza la versión detectada e investiga si existen vulnerabilidades conocidas asociadas. robots.php',
        'herramientas' => ['NVD', 'análisis de versiones', 'searchsploit','CVEs conocidas','Nmap -sV','Inspección de pagina de servicio.'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto11-metasploit',
        'numero' => 11,
        'titulo' => 'Explotacion con Metasploit',
        'categoria' => 'Explotacion',
        'dificultad' => 'Alta',
        'puntaje' => 225,
        'objetivo' => 'Un servidor legado permanece activo dentro del entorno de pruebas de la organización. 
            Informes previos indican que el servicio IRC podría contener una vulnerabilidad 
            crítica utilizada históricamente para ejecución remota de comandos. 
            Obtén acceso al sistema y recupera la evidencia solicitada.',
        'herramientas' => ['Nmap', 'Metasploit Framework', 'msfconsole', 'payloads UNIX', 'reconocimiento de servicios', 'explotación remota'],
        'estado' => 'Disponible',
    ],
    [
        'slug' => 'reto12-privesc',
        'numero' => 12,
        'titulo' => 'Escalada de privilegios',
        'categoria' => 'Post explotacion',
        'dificultad' => 'Experto',
        'puntaje' => 300,
        'objetivo' => 'Elevar permisos dentro del sistema comprometido hasta obtener acceso de administrador o root y cerrar la cadena de ataque.',
        'herramientas' => ['linpeas', 'sudo abuse', 'misconfiguraciones locales'],
        'estado' => 'Disponible',
    ],
];
